# Generated by Django 3.2.3 on 2021-05-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='learn_django',
        ),
    ]
