# Generated by Django 3.2.3 on 2021-05-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_employee_learn_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='learn_django',
        ),
    ]
